ALTER TABLE "Provider" ADD COLUMN "rfcDocumentUrl" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Provider" ADD COLUMN "rntDocumentUrl" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Provider" ADD COLUMN "ineDocumentUrl" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Provider" ADD COLUMN "fiscalAddressProofUrl" TEXT NOT NULL DEFAULT '';

ALTER TABLE "Agency" ADD COLUMN "rfcDocumentUrl" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Agency" ADD COLUMN "rntDocumentUrl" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Agency" ADD COLUMN "ineDocumentUrl" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Agency" ADD COLUMN "fiscalAddressProofUrl" TEXT NOT NULL DEFAULT '';
